name: 'CodeQL Customization'
description: 'Customize the default queries to add sources, sinks, taint steps, ...'
inputs:
  qll:
    description: 'Customizations as a CodeQL library'
    required: true
  language:
    description: 'Language of the database to analyze'
    required: true
  search-path:
    description: 'A list of colon-separated directories containing the query packs which shall be customized'
    required: false
runs:
  using: "composite"
  steps:
    - name: customize
      run: |
        python3 "${{ github.action_path }}/customize" --qll "${{ inputs.qll }}" --language "${{ inputs.language }}" --search-path "${{ inputs.search-path }}"
      shell: bash
